### ISSUE TITLE
optimizeXcmsSet expects parameters that are not even used by and related to centWave

### ISSUE THREAD

**Issue by etrh** [rietho/IPO#57]
When working with `optimizeXcmsSet` to optimize `centWave` parameters, `optimizeXcmsSet` requires several parameters that are not even related to `centWave`.

```
Error in checkParams(params, quantitative_parameters, qualitative_parameters,  : 
  The parameter(s) fwhm, sigma, max, steps, index is/are missing! Please specify; stopping! 
```

Any plans to fix this?

**Comment by rietho** [comment]
Hi!

Unfortunately the package IPO is at the moment in an [unsupported](http://www.repostatus.org/#unsupported) status. Thus, I can only offer very limited support.

However, it seems that there happened an error in your parameter specification. I guess that you specified a parameter `step`, which lets IPO think that you want to use the `matchedFilter` method. If you need further help, please post your full code, so that it's possible to see what might have gone wrong.

**Comment by etrh** [comment]
`step` was indeed the problem which I had erroneously added to the list of parameters. Removing it no longer throws an error. Thanks a lot.
